import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.DatePicker;
import javafx.scene.control.RadioButton;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleGroup;

public class CreateTournamentController {

    @FXML
    private ToggleGroup TournamentSport;

    @FXML
    private RadioButton TournamentSportChooseFootball;

    @FXML
    private RadioButton TournamentSportChooseTennis;

    @FXML
    private RadioButton TournamentSportChooseVolleyball;

    @FXML
    private DatePicker datePickerCreateTournament;

    @FXML
    private TextField tournamentHourField;

    @FXML
    private TextField tournamentNameField;

    @FXML
    void BackCreateTournamentPage(ActionEvent event) {

    }

    @FXML
    void CreateTheTournament(ActionEvent event) {

    }

    @FXML
    void SidebarCreateTournamentPage(ActionEvent event) {
        
    }

    @FXML
    void getDate(ActionEvent event) {

    }

    @FXML
    void getSport(ActionEvent event) {

    }

}